'use client';

import { useState, useEffect } from 'react';
import { getTopicImagePaths, saveTopicFile, deleteTopicImage, generateDescriptionForExistingImage, updateTopicFileDescription } from '@/lib/topicImages';

interface TopicFileSectionProps {
  editingTopicId: string | null;
  meetingId: string;
  organizationId: string;
}

export default function TopicFileSection({
  editingTopicId,
  meetingId,
  organizationId,
}: TopicFileSectionProps) {
  const [topicFiles, setTopicFiles] = useState<Array<{ path: string; description?: string; detailedDescription?: string; id?: string; fileName?: string; mimeType?: string; fileSize?: number }>>([]);
  const [isLoadingFiles, setIsLoadingFiles] = useState(false);
  const [uploadingFile, setUploadingFile] = useState(false);
  const [fileDescription, setFileDescription] = useState('');
  const [autoGenerateDescription, setAutoGenerateDescription] = useState(false);
  const [useLocalVLM, setUseLocalVLM] = useState(false);
  const [useDirectLFM2, setUseDirectLFM2] = useState(false);
  const [vlmModel, setVlmModel] = useState<string>('gpt-4o');
  const [availableVlmModels, setAvailableVlmModels] = useState<Array<{ value: string; label: string }>>([]);
  const [loadingVlmModels, setLoadingVlmModels] = useState(false);
  const [generatingDescriptionFor, setGeneratingDescriptionFor] = useState<string | null>(null);
  const [showDeleteFileModal, setShowDeleteFileModal] = useState(false);
  const [fileToDelete, setFileToDelete] = useState<{ path: string; fileName: string } | null>(null);
  const [editingFileDescription, setEditingFileDescription] = useState<{ path: string; description: string; detailedDescription: string } | null>(null);

  // トピックIDが確定したらファイルを読み込む
  useEffect(() => {
    if (editingTopicId) {
      loadTopicFiles();
    } else {
      setTopicFiles([]);
    }
  }, [editingTopicId]);

  // VLMモデルリストを読み込む
  useEffect(() => {
    const loadVlmModels = async () => {
      // GPT Vision対応モデル
      const gptVisionModels = [
        { value: 'gpt-4o', label: 'GPT-4o (Vision)' },
        { value: 'gpt-4o-mini', label: 'GPT-4o Mini (Vision)' },
        { value: 'gpt-4-turbo', label: 'GPT-4 Turbo (Vision)' },
      ];

      // ローカルVLMモデルを取得
      if (useLocalVLM) {
        setLoadingVlmModels(true);
        try {
          const { getAvailableOllamaModels } = await import('@/lib/pageGeneration');
          const localModels = await getAvailableOllamaModels();
          const vlmModels = localModels
            .filter(model => {
              const nameLower = model.name.toLowerCase();
              return nameLower.includes('llava') || 
                     nameLower.includes('vision') ||
                     nameLower.includes('vlm') ||
                     nameLower.includes('bakllava') ||
                     nameLower.includes('moondream') ||
                     nameLower.includes('lfm2') ||
                     nameLower.includes('lfm');
            })
            .map(model => ({ value: model.name, label: model.name }));
          
          setAvailableVlmModels(vlmModels.length > 0 ? vlmModels : [{ value: 'llava:latest', label: 'llava:latest' }]);
        } catch (error) {
          console.error('ローカルVLMモデルの取得エラー:', error);
          setAvailableVlmModels([{ value: 'llava:latest', label: 'llava:latest' }]);
        } finally {
          setLoadingVlmModels(false);
        }
      } else {
        setAvailableVlmModels(gptVisionModels);
      }
    };

    loadVlmModels();
  }, [useLocalVLM]);

  // モデルタイプが変更されたら、デフォルトモデルを設定
  useEffect(() => {
    if (useLocalVLM) {
      // ローカルVLMの場合、最初のモデルを選択
      if (availableVlmModels.length > 0) {
        setVlmModel(availableVlmModels[0].value);
      } else {
        setVlmModel('llava:latest');
      }
    } else {
      // GPT Visionの場合
      setVlmModel('gpt-4o');
    }
  }, [useLocalVLM, availableVlmModels]);

  const loadTopicFiles = async () => {
    if (!editingTopicId || !meetingId) return;
    setIsLoadingFiles(true);
    try {
      const files = await getTopicImagePaths(editingTopicId, meetingId);
      console.log('読み込んだファイル:', files); // デバッグ用
      setTopicFiles(files);
    } catch (error) {
      console.error('ファイルの読み込みエラー:', error);
    } finally {
      setIsLoadingFiles(false);
    }
  };

  const handleFileUpload = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file || !editingTopicId || !meetingId) return;

    setUploadingFile(true);
    try {
      const result = await saveTopicFile(
        organizationId,
        editingTopicId,
        meetingId,
        file,
        fileDescription.trim() || undefined,
        autoGenerateDescription,
        useLocalVLM,
        vlmModel,
        useDirectLFM2,
        editingTopicId
      );

      if (result.success) {
        // ファイルリストを再読み込み
        await loadTopicFiles();
        
        // 自動生成された説明がある場合は表示（アラートのみ、フォームには残さない）
        if (result.generatedDescription) {
          const detailMsg = result.generatedDetailedDescription 
            ? `\n\n詳細解説:\n${result.generatedDetailedDescription}`
            : '';
          alert(`ファイルを保存しました。\n\n自動生成された説明（RAG検索用）:\n${result.generatedDescription}${detailMsg}`);
        } else {
          alert('ファイルを保存しました。');
        }
        
        // 説明文入力フォームをクリア（次のアップロードに影響しないように）
        setFileDescription('');
        
        // ファイル入力のリセット
        event.target.value = '';
      } else {
        alert(`ファイルの保存に失敗しました: ${result.error}`);
      }
    } catch (error: any) {
      console.error('ファイルアップロードエラー:', error);
      alert(`ファイルのアップロードに失敗しました: ${error?.message || '不明なエラー'}`);
    } finally {
      setUploadingFile(false);
    }
  };

  const handleDeleteFileClick = (filePath: string) => {
    const fileName = filePath.split('/').pop() || filePath;
    setFileToDelete({ path: filePath, fileName });
    setShowDeleteFileModal(true);
  };

  const handleConfirmDeleteFile = async () => {
    if (!fileToDelete || !editingTopicId || !meetingId) return;

    try {
      await deleteTopicImage(organizationId, editingTopicId, meetingId, fileToDelete.path);
      await loadTopicFiles();
      setShowDeleteFileModal(false);
      setFileToDelete(null);
      alert('ファイルを削除しました。');
    } catch (error: any) {
      console.error('ファイル削除エラー:', error);
      alert(`ファイルの削除に失敗しました: ${error?.message || '不明なエラー'}`);
    }
  };

  const handleCancelDeleteFile = () => {
    setShowDeleteFileModal(false);
    setFileToDelete(null);
  };

  const handleGenerateDescription = async (filePath: string) => {
    if (!editingTopicId || !meetingId) return;

    setGeneratingDescriptionFor(filePath);
    try {
      const result = await generateDescriptionForExistingImage(
        organizationId,
        editingTopicId,
        meetingId,
        filePath,
        useLocalVLM,
        vlmModel,
        useDirectLFM2
      );

      if (result.success && result.description) {
        // 詳細解説も取得して表示
        const files = await getTopicImagePaths(editingTopicId, meetingId);
        const fileInfo = files.find(f => f.path === filePath);
        const detailMsg = fileInfo?.detailedDescription 
          ? `\n\n詳細解説:\n${fileInfo.detailedDescription}`
          : '';
        alert(`説明を生成しました:\n\n説明文（RAG検索用）:\n${result.description}${detailMsg}`);
        await loadTopicFiles(); // ファイルリストを再読み込み
      } else {
        alert(`説明の生成に失敗しました: ${result.error || '不明なエラー'}`);
      }
    } catch (error: any) {
      console.error('説明生成エラー:', error);
      alert(`説明の生成中にエラーが発生しました: ${error?.message || '不明なエラー'}`);
    } finally {
      setGeneratingDescriptionFor(null);
    }
  };

  const handleOpenFile = async (filePath: string) => {
    try {
      // Tauri環境でファイルを開く
      const isTauri = typeof window !== 'undefined' && '__TAURI__' in window;
      if (isTauri) {
        // Rustコマンドでファイルを開く
        const { callTauriCommand } = await import('@/lib/localFirebase');
        const result = await callTauriCommand('open_file', { filePath });
        
        if (result && !result.success) {
          throw new Error(result.error || 'ファイルを開けませんでした');
        }
      } else {
        alert('Tauri環境でのみファイルを開くことができます。');
      }
    } catch (error: any) {
      console.error('ファイルを開くエラー:', error);
      alert(`ファイルを開けませんでした: ${error?.message || '不明なエラー'}`);
    }
  };

  if (!editingTopicId) {
    return null;
  }

  // ファイル名を抽出する関数
  const getFileIcon = (name: string) => {
    const ext = name.split('.').pop()?.toLowerCase() || '';
    if (['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg'].includes(ext)) return '📷';
    if (['pdf'].includes(ext)) return '📄';
    if (['xlsx', 'xls'].includes(ext)) return '📊';
    if (['docx', 'doc'].includes(ext)) return '📝';
    if (['txt', 'md'].includes(ext)) return '📃';
    return '📎';
  };

  return (
    <>
      <div style={{ marginBottom: '24px', borderTop: '1px solid #e5e7eb', paddingTop: '24px' }}>
        <div style={{ fontSize: '14px', color: '#6B7280', fontWeight: 600, marginBottom: '12px' }}>
          📎 ファイル
        </div>
        
        {/* ファイルアップロード */}
        <div style={{ marginBottom: '16px', padding: '16px', backgroundColor: '#F9FAFB', borderRadius: '8px', border: '1px solid #E5E7EB' }}>
          <div style={{ marginBottom: '8px' }}>
            <label style={{ display: 'block', fontSize: '12px', color: '#6B7280', marginBottom: '4px' }}>
              ファイルの説明文（RAG検索用）
            </label>
            <input
              type="text"
              value={fileDescription}
              onChange={(e) => setFileDescription(e.target.value)}
              placeholder="例: プロジェクト進捗のグラフ、会議資料のPDF、Excelデータなど"
              style={{
                width: '100%',
                padding: '8px 12px',
                border: '1px solid #e5e7eb',
                borderRadius: '4px',
                fontSize: '14px',
                boxSizing: 'border-box',
              }}
            />
          </div>
          
          {/* 自動生成オプション */}
          <div style={{ marginBottom: '12px', display: 'flex', flexDirection: 'column', gap: '8px' }}>
            <label style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '13px', color: '#374151', cursor: 'pointer' }}>
              <input
                type="checkbox"
                checked={autoGenerateDescription}
                onChange={(e) => setAutoGenerateDescription(e.target.checked)}
                style={{ cursor: 'pointer' }}
              />
              <span>画像の場合、VLMで説明を自動生成</span>
            </label>
            {autoGenerateDescription && (
              <>
                <label style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '12px', color: '#6B7280', cursor: 'pointer', marginLeft: '24px' }}>
                  <input
                    type="checkbox"
                    checked={useLocalVLM}
                    onChange={(e) => setUseLocalVLM(e.target.checked)}
                    style={{ cursor: 'pointer' }}
                  />
                  <span>ローカルVLM（Liquid AI）を使用（未チェック時はGPT-4 Visionを使用）</span>
                </label>
                {loadingVlmModels ? (
                  <div style={{ marginLeft: '24px', fontSize: '12px', color: '#6B7280' }}>
                    🔄 モデルを読み込み中...
                  </div>
                ) : availableVlmModels.length > 0 && (
                  <div style={{ marginLeft: '24px', display: 'flex', flexDirection: 'column', gap: '8px' }}>
                    <div style={{ display: 'flex', flexDirection: 'column', gap: '4px' }}>
                      <label style={{ fontSize: '12px', color: '#6B7280' }}>
                        VLMモデル:
                      </label>
                      <select
                        value={vlmModel}
                        onChange={(e) => setVlmModel(e.target.value)}
                        style={{
                          padding: '6px 10px',
                          border: '1px solid #D1D5DB',
                          borderRadius: '4px',
                          fontSize: '12px',
                          backgroundColor: '#FFFFFF',
                          color: '#374151',
                          cursor: 'pointer',
                          minWidth: '200px',
                        }}
                      >
                        {availableVlmModels.map((model) => (
                          <option key={model.value} value={model.value}>
                            {model.label}
                          </option>
                        ))}
                      </select>
                    </div>
                    {(vlmModel.includes('lfm2') || vlmModel.includes('LFM2')) && (
                      <label style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '12px', color: '#6B7280', cursor: 'pointer' }}>
                        <input
                          type="checkbox"
                          checked={useDirectLFM2}
                          onChange={(e) => setUseDirectLFM2(e.target.checked)}
                          style={{ cursor: 'pointer' }}
                        />
                        <span>Ollama経由ではなく直接使用（Pythonスクリプト経由）</span>
                      </label>
                    )}
                  </div>
                )}
              </>
            )}
          </div>
          
          <label
            style={{
              display: 'inline-block',
              padding: '8px 16px',
              backgroundColor: uploadingFile ? '#94A3B8' : '#3B82F6',
              color: '#FFFFFF',
              border: 'none',
              borderRadius: '6px',
              fontSize: '14px',
              fontWeight: 500,
              cursor: uploadingFile ? 'not-allowed' : 'pointer',
              transition: 'background-color 0.2s',
            }}
          >
            {uploadingFile ? 'アップロード中...' : '📎 ファイルを選択'}
            <input
              type="file"
              onChange={handleFileUpload}
              disabled={uploadingFile}
              style={{ display: 'none' }}
            />
          </label>
        </div>
        
        {/* アップロード済みファイルの表示 */}
        {isLoadingFiles ? (
          <div style={{ padding: '12px', backgroundColor: '#F9FAFB', borderRadius: '8px', fontSize: '14px', color: '#6B7280' }}>
            読み込み中...
          </div>
        ) : topicFiles.length > 0 ? (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
            {topicFiles.map((file, index) => {
              const fileName = file.path.split('/').pop() || file.path;
              return (
                <div
                  key={index}
                  style={{
                    position: 'relative',
                    padding: '12px',
                    backgroundColor: '#FFFFFF',
                    borderRadius: '8px',
                    border: '1px solid #E5E7EB',
                    boxShadow: '0 1px 3px rgba(0, 0, 0, 0.1)',
                  }}
                >
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: '12px' }}>
                    <div style={{ flex: 1 }}>
                      <div style={{ marginBottom: '4px' }}>
                        <div
                          onClick={() => handleOpenFile(file.path)}
                          style={{
                            fontSize: '14px',
                            fontWeight: 600,
                            color: '#0066CC',
                            cursor: 'pointer',
                            textDecoration: 'underline',
                            display: 'inline-block',
                            marginBottom: '2px',
                          }}
                          onMouseEnter={(e) => {
                            e.currentTarget.style.color = '#0051a8';
                          }}
                          onMouseLeave={(e) => {
                            e.currentTarget.style.color = '#0066CC';
                          }}
                        >
                          {getFileIcon(fileName)} {file.fileName || fileName}
                        </div>
                        {(file.mimeType || file.fileSize) && (
                          <div style={{ fontSize: '10px', color: '#9CA3AF', marginTop: '2px' }}>
                            {file.mimeType && <span>{file.mimeType}</span>}
                            {file.mimeType && file.fileSize && <span> • </span>}
                            {file.fileSize && <span>{(file.fileSize / 1024).toFixed(1)} KB</span>}
                          </div>
                        )}
                        {file.id && (
                          <div style={{ fontSize: '10px', color: '#9CA3AF', fontFamily: 'monospace', marginTop: '2px' }}>
                            ID: {file.id}
                          </div>
                        )}
                      </div>
                      {(file.description || file.detailedDescription || editingFileDescription?.path === file.path) && (
                        <div style={{ marginBottom: '8px' }}>
                          {editingFileDescription?.path === file.path ? (
                            // 編集モード
                            <>
                              <div style={{ fontSize: '12px', color: '#6B7280', fontWeight: 600, marginBottom: '4px' }}>
                                📝 説明文（RAG検索用）:
                              </div>
                              <textarea
                                value={editingFileDescription.description}
                                onChange={(e) => setEditingFileDescription({
                                  ...editingFileDescription,
                                  description: e.target.value,
                                })}
                                style={{
                                  width: '100%',
                                  fontSize: '12px',
                                  padding: '6px',
                                  border: '1px solid #D1D5DB',
                                  borderRadius: '4px',
                                  marginBottom: '12px',
                                  resize: 'vertical',
                                  minHeight: '60px',
                                }}
                                placeholder="RAG検索用の簡潔な説明文を入力"
                              />
                              <div style={{ fontSize: '12px', color: '#6B7280', fontWeight: 600, marginBottom: '4px' }}>
                                📖 詳細解説:
                              </div>
                              <textarea
                                value={editingFileDescription.detailedDescription}
                                onChange={(e) => setEditingFileDescription({
                                  ...editingFileDescription,
                                  detailedDescription: e.target.value,
                                })}
                                style={{
                                  width: '100%',
                                  fontSize: '12px',
                                  padding: '6px',
                                  border: '1px solid #D1D5DB',
                                  borderRadius: '4px',
                                  marginBottom: '8px',
                                  resize: 'vertical',
                                  minHeight: '120px',
                                }}
                                placeholder="詳細な解説を入力"
                              />
                              <div style={{ display: 'flex', gap: '8px', marginTop: '8px' }}>
                                <button
                                  onClick={async () => {
                                    if (!editingTopicId || !meetingId) return;
                                    try {
                                      await updateTopicFileDescription(
                                        organizationId,
                                        editingTopicId,
                                        meetingId,
                                        file.path,
                                        editingFileDescription.description,
                                        editingFileDescription.detailedDescription
                                      );
                                      await loadTopicFiles();
                                      setEditingFileDescription(null);
                                      alert('説明文を更新しました。');
                                    } catch (error: any) {
                                      console.error('説明文の更新エラー:', error);
                                      alert(`説明文の更新に失敗しました: ${error?.message || '不明なエラー'}`);
                                    }
                                  }}
                                  style={{
                                    padding: '6px 12px',
                                    backgroundColor: '#3B82F6',
                                    color: '#FFFFFF',
                                    border: 'none',
                                    borderRadius: '4px',
                                    fontSize: '12px',
                                    cursor: 'pointer',
                                    fontWeight: 500,
                                  }}
                                >
                                  保存
                                </button>
                                <button
                                  onClick={() => setEditingFileDescription(null)}
                                  style={{
                                    padding: '6px 12px',
                                    backgroundColor: '#6B7280',
                                    color: '#FFFFFF',
                                    border: 'none',
                                    borderRadius: '4px',
                                    fontSize: '12px',
                                    cursor: 'pointer',
                                    fontWeight: 500,
                                  }}
                                >
                                  キャンセル
                                </button>
                              </div>
                            </>
                          ) : (
                            // 表示モード
                            <>
                              {file.description && (
                                <>
                                  <div style={{ fontSize: '12px', color: '#6B7280', fontWeight: 600, marginBottom: '4px' }}>
                                    📝 説明文（RAG検索用）:
                                  </div>
                                  <div style={{ fontSize: '12px', color: '#6B7280', wordBreak: 'break-word', marginBottom: file.detailedDescription ? '12px' : '0' }}>
                                    {file.description}
                                  </div>
                                </>
                              )}
                              {file.detailedDescription && (
                                <>
                                  <div style={{ fontSize: '12px', color: '#6B7280', fontWeight: 600, marginTop: file.description ? '8px' : '0', marginBottom: '4px' }}>
                                    📖 詳細解説:
                                  </div>
                                  <div style={{ fontSize: '12px', color: '#4B5563', wordBreak: 'break-word', lineHeight: '1.6', padding: '8px', backgroundColor: '#F9FAFB', borderRadius: '4px', border: '1px solid #E5E7EB' }}>
                                    {file.detailedDescription}
                                  </div>
                                </>
                              )}
                            </>
                          )}
                        </div>
                      )}
                      <div style={{ fontSize: '11px', color: '#9CA3AF', fontFamily: 'monospace', wordBreak: 'break-all' }}>
                        {file.path}
                      </div>
                      {file.id && (
                        <div style={{ fontSize: '10px', color: '#9CA3AF', fontFamily: 'monospace', marginTop: '4px' }}>
                          ID: {file.id}
                        </div>
                      )}
                    </div>
                    <div style={{ display: 'flex', gap: '8px', flexShrink: 0 }}>
                      {/* 編集モードでない場合にボタンを表示 */}
                      {editingFileDescription?.path !== file.path && (
                        <>
                          {/* 説明文の編集ボタン（削除ボタンの左側） */}
                          <button
                            onClick={() => setEditingFileDescription({
                              path: file.path,
                              description: file.description || '',
                              detailedDescription: file.detailedDescription || '',
                            })}
                            style={{
                              padding: '6px 12px',
                              backgroundColor: '#F3F4F6',
                              color: '#374151',
                              border: '1px solid #D1D5DB',
                              borderRadius: '6px',
                              fontSize: '12px',
                              cursor: 'pointer',
                              fontWeight: 500,
                            }}
                          >
                            {file.description || file.detailedDescription ? '編集' : '説明追加'}
                          </button>
                          {/* 画像ファイルの場合のみ説明生成ボタンを表示 */}
                          {/\.(jpg|jpeg|png|gif|webp|svg)$/i.test(fileName) && (
                            <button
                              onClick={() => handleGenerateDescription(file.path)}
                              disabled={generatingDescriptionFor === file.path}
                              style={{
                                padding: '6px 12px',
                                backgroundColor: generatingDescriptionFor === file.path ? '#94A3B8' : '#10B981',
                                color: '#FFFFFF',
                                border: 'none',
                                borderRadius: '6px',
                                fontSize: '12px',
                                cursor: generatingDescriptionFor === file.path ? 'not-allowed' : 'pointer',
                                fontWeight: 500,
                              }}
                            >
                              {generatingDescriptionFor === file.path ? '生成中...' : '説明生成'}
                            </button>
                          )}
                          {/* 削除ボタン */}
                          <button
                            onClick={() => handleDeleteFileClick(file.path)}
                            style={{
                              padding: '6px 12px',
                              backgroundColor: '#EF4444',
                              color: '#FFFFFF',
                              border: 'none',
                              borderRadius: '6px',
                              fontSize: '12px',
                              cursor: 'pointer',
                              fontWeight: 500,
                            }}
                          >
                            削除
                          </button>
                        </>
                      )}
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        ) : (
          <div style={{ padding: '12px', backgroundColor: '#F9FAFB', borderRadius: '8px', fontSize: '14px', color: '#9CA3AF', fontStyle: 'italic', textAlign: 'center' }}>
            ファイルがありません
          </div>
        )}
      </div>

      {/* ファイル削除確認モーダル */}
      {showDeleteFileModal && fileToDelete && (
        <div
          style={{
            position: 'fixed',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            background: 'rgba(0, 0, 0, 0.5)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            zIndex: 3000,
          }}
          onClick={handleCancelDeleteFile}
        >
          <div
            style={{
              backgroundColor: '#FFFFFF',
              borderRadius: '12px',
              padding: '24px',
              maxWidth: '500px',
              width: '90%',
              boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1)',
            }}
            onClick={(e) => e.stopPropagation()}
          >
            <h3 style={{ fontSize: '18px', fontWeight: 600, color: '#1a1a1a', marginBottom: '16px' }}>
              ファイルを削除しますか？
            </h3>
            <div style={{ marginBottom: '20px' }}>
              <div style={{ fontSize: '14px', color: '#6B7280', marginBottom: '8px' }}>
                ファイル名:
              </div>
              <div style={{ fontSize: '14px', fontWeight: 500, color: '#1a1a1a', marginBottom: '12px' }}>
                {fileToDelete.fileName}
              </div>
              <div style={{ fontSize: '12px', color: '#9CA3AF', fontFamily: 'monospace', wordBreak: 'break-all' }}>
                {fileToDelete.path}
              </div>
            </div>
            <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '12px' }}>
              <button
                onClick={handleCancelDeleteFile}
                style={{
                  padding: '10px 20px',
                  backgroundColor: '#F3F4F6',
                  color: '#374151',
                  border: 'none',
                  borderRadius: '8px',
                  fontSize: '14px',
                  fontWeight: 500,
                  cursor: 'pointer',
                }}
              >
                キャンセル
              </button>
              <button
                onClick={handleConfirmDeleteFile}
                style={{
                  padding: '10px 20px',
                  backgroundColor: '#EF4444',
                  color: '#FFFFFF',
                  border: 'none',
                  borderRadius: '8px',
                  fontSize: '14px',
                  fontWeight: 500,
                  cursor: 'pointer',
                }}
              >
                削除する
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}

